import { flashcards, stageMeta, type Chapter, type Stage } from "@/data/jee";
import { Check, ChevronRight, StickyNote, X } from "lucide-react";
import { useState } from "react";

const stages: Stage[] = ["not_started", "revising", "revised", "test_ready"];

export function ChapterDetail({ chapter, onClose, onUpdate, onAdvance }: { chapter: Chapter; onClose: () => void; onUpdate: (id: string, patch: Partial<Chapter>) => void; onAdvance: (chapter: Chapter) => void }) {
  const [notes, setNotes] = useState(chapter.notes ?? "");
  const formulas = flashcards.filter((card) => card.chapterId === chapter.id);
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#2E180F]/40 p-4 backdrop-blur-sm"><div className="mx-auto my-6 w-full max-w-2xl rounded-[1.8rem] bg-[#FFFDF9] p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="jee-kicker">{chapter.subject} · target week {chapter.targetWeek}</p><h2 className="jee-title mt-1 text-3xl">{chapter.title}</h2></div><button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-[#F5E8DB]"><X className="size-4" /></button></div><div className="mt-6 grid gap-5 md:grid-cols-[1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-wider text-[#85644F]">Mastery stage</p><div className="mt-3 flex gap-2">{stages.map((stage) => <button key={stage} onClick={() => onUpdate(chapter.id, { stage })} className={`rounded-full px-3 py-2 text-xs font-bold ${chapter.stage === stage ? "bg-[#4D2A1D] text-white" : "bg-[#F7EBDD] text-[#815E48]"}`}>{stageMeta[stage].label}</button>)}</div><button onClick={() => onAdvance(chapter)} className="mt-4 rounded-xl bg-[#D49A50] px-4 py-2.5 text-xs font-bold text-white">Advance stage <ChevronRight className="inline size-3.5" /></button><div className="mt-6 rounded-2xl bg-[#F8EBDD] p-4"><div className="flex items-center gap-2"><StickyNote className="size-4 text-[#9B623E]" /><p className="text-xs font-bold text-[#805638]">Mistake & revision notes</p></div><textarea value={notes} onChange={(event) => setNotes(event.target.value)} onBlur={() => onUpdate(chapter.id, { notes })} placeholder="Log a misconception, a formula cue, or a reminder for the next revision…" className="mt-3 min-h-28 w-full resize-none rounded-xl border border-[#E5D3C0] bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-[#D6A56E]/50" /></div></div><div><p className="text-xs font-bold uppercase tracking-wider text-[#85644F]">Relevant formula cards</p><div className="mt-3 space-y-3">{formulas.length ? formulas.map((formula) => <div key={formula.id} className="rounded-2xl border border-[#E8D7C6] bg-white p-4"><p className="text-xs font-bold text-[#9B623E]">{formula.front}</p><p className="jee-title mt-2 text-lg">{formula.back}</p></div>) : <div className="rounded-2xl bg-[#F4EEE6] p-4 text-sm leading-6 text-[#876955]">Add a formula card for this chapter as you build your personal revision library.</div>}</div></div></div><div className="mt-6 flex items-center justify-between rounded-2xl bg-[#F6E2C7] p-4"><span className="text-sm font-semibold text-[#684532]">{chapter.flagged ? "This chapter is flagged for review." : "This chapter is not flagged."}</span><button onClick={() => onUpdate(chapter.id, { flagged: !chapter.flagged })} className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-[#76523D]">{chapter.flagged ? "Remove flag" : "Flag for review"}</button></div></div></div>;
}
