import { ChartNoAxesCombined, CircleAlert, TrendingDown } from "lucide-react";

type Mock = { physics: number; chemistry: number; mathematics: number; total: number; attemptedAt: Date };

export function MarksLossAnalysis({ mocks }: { mocks: Mock[] }) {
  if (mocks.length < 2) return <section className="today-panel p-5 sm:p-6"><p className="today-kicker text-[#FF4FA7]"><ChartNoAxesCombined className="size-3.5" /> Marks-loss analysis</p><h3 className="today-heading mt-2">More evidence needed.</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">Log at least two mocks to compare subject splits. Add a post-mortem to identify calculation, conceptual, time-management, or avoidable-error patterns without guessing.</p></section>;
  const average = (key: "physics" | "chemistry" | "mathematics") => Math.round(mocks.reduce((sum, mock) => sum + mock[key], 0) / mocks.length);
  const subjectScores = [{ subject: "Physics", score: average("physics") }, { subject: "Chemistry", score: average("chemistry") }, { subject: "Mathematics", score: average("mathematics") }].sort((a, b) => a.score - b.score);
  const latest = mocks[mocks.length - 1]; const prior = mocks[mocks.length - 2]; const totalDelta = latest.total - prior.total;
  return <section className="today-panel p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="today-kicker text-[#FF4FA7]"><TrendingDown className="size-3.5" /> Marks-loss analysis</p><h3 className="today-heading mt-2">What the recorded scores can prove.</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">This analysis reports only subject-split evidence. Use the post-mortem below to attach the actual causes behind any lost marks.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-white/35">Recent total shift</p><p className={`mt-1 text-2xl font-black ${totalDelta >= 0 ? "text-[#C7FF3C]" : "text-[#FF4FA7]"}`}>{totalDelta >= 0 ? "+" : ""}{totalDelta} marks</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-3">{subjectScores.map((item, index) => <div key={item.subject} className={`rounded-2xl border p-4 ${index === 0 ? "border-[#FF4FA7]/35 bg-[#FF4FA7]/[.07]" : "border-white/10 bg-white/[.03]"}`}><p className="text-xs font-bold text-white/70">{item.subject}</p><p className="mt-2 text-3xl font-black text-white">{item.score}<span className="text-sm text-white/40"> / 100</span></p><p className="mt-2 text-[11px] leading-5 text-white/45">{index === 0 ? "Lowest recorded subject average. Pair it with a chapter-level post-mortem before changing your plan." : "Recorded average across logged mocks."}</p></div>)}</div><div className="mt-4 flex items-start gap-2 rounded-2xl border border-[#FFC84A]/25 bg-[#FFC84A]/[.06] p-4 text-xs leading-5 text-white/60"><CircleAlert className="mt-0.5 size-4 shrink-0 text-[#FFC84A]" />We cannot infer negative marking, attempt rate, silly mistakes, or time-management problems from subject totals alone. Add those observations in the mock post-mortem to make the next AI analysis more specific.</div></section>;
}
