import { trpc } from "@/lib/trpc";
import { CopilotResponse } from "@/components/CopilotResponse";
import { BrainCircuit, FileSearch, Sparkles } from "lucide-react";
import { useState } from "react";

export function MockPostMortem({ total, mockCount }: { total: number; mockCount: number }) {
  const [wrong, setWrong] = useState(""); const [guessed, setGuessed] = useState(""); const [skipped, setSkipped] = useState(""); const [difficultCorrect, setDifficultCorrect] = useState("");
  const analysis = trpc.ai.mockPostMortem.useMutation();
  const canAnalyse = mockCount > 0 && (wrong.trim() || guessed.trim() || skipped.trim() || difficultCorrect.trim());
  const fields = [["Wrong answers / concepts", wrong, setWrong, "e.g., torque sign convention, integration substitution"], ["Guessed", guessed, setGuessed, "e.g., 3 electrochemistry questions"], ["Skipped", skipped, setSkipped, "e.g., lengthy coordinate geometry set"], ["Correct but difficult", difficultCorrect, setDifficultCorrect, "e.g., one rotational motion question"]] as const;

  return <section className="today-panel p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="today-kicker text-[#FF4FA7]"><FileSearch className="size-3.5" /> Mock post-mortem</p><h3 className="today-heading mt-2">Where marks are going.</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">Log what actually happened before analysis. Copilot will explain the recorded evidence; it will not invent accuracy, negative marks, or error counts.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/35">Latest mock</p><p className="mt-1 text-2xl font-black text-white">{total}<span className="text-sm text-white/40"> / 300</span></p></div></div>{mockCount < 1 ? <div className="mt-6 rounded-2xl border border-dashed border-white/15 p-5 text-sm leading-6 text-white/45">No mock data yet. Log a first mock to unlock a useful post-mortem rather than a generic analysis.</div> : <><div className="mt-6 grid gap-3 md:grid-cols-2">{fields.map(([label, value, setter, placeholder]) => <label key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><span className="text-[10px] font-bold uppercase tracking-[.15em] text-white/40">{label}</span><textarea value={value} onChange={(event) => setter(event.target.value)} placeholder={placeholder} className="mt-3 min-h-20 w-full resize-none bg-transparent text-sm text-white outline-none placeholder:text-white/25" /></label>)}</div><button disabled={!canAnalyse || analysis.isPending} onClick={() => analysis.mutate({ mockTotal: total, wrong, guessed, skipped, difficultCorrect })} className="today-action mt-4 disabled:opacity-40"><BrainCircuit className="size-4" />{analysis.isPending ? "Reading recorded evidence…" : "Analyse this mock"}</button>{analysis.data && <div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4 text-white/80"><CopilotResponse content={analysis.data} /></div>}{analysis.error && <div className="mt-5 rounded-2xl border border-[#FF4FA7]/30 bg-[#FF4FA7]/10 p-4 text-sm text-white/70"><Sparkles className="mr-1 inline size-4" />Analysis is unavailable right now. Your observations remain useful notes for the next revision block.</div>}</>}</section>;
}
